git:
  parseEmoji: true

gui:
  showIcons: true

os:
  editPreset: "nvim"

customCommands:
  - key: "<c-c>"
    context: "files"
    description: 'commit files with format'
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: ':ambulance:'
            description: '(fix) ğŸš‘ Fatal bug fix'
            value: ':ambulance: fix:'
          - name: ':bug:'
            description: '(fix) ğŸ› Bug fix'
            value: ':bug: fix:'
          - name: ':+1:'
            description: '(fix) ğŸ‘ Functional improvements and corrections'
            value: ':+1: fix:'
          - name: ':cop:'
            description: '(fix) ğŸ‘® Security related fixes'
            value: ':cop: fix:'
          - name: ':tada'
            description: '(feat) ğŸ‰ Big feature addition'
            value: ':tada: feat:'
          - name: ':sparkles:'
            description: '(feat) âœ¨ Partial function addition'
            value: ':sparkles: feat:'
          - name: ':up:'
            description: '(feat) ğŸ†™ Update of dependent packages, etc'
            value: ':up: feat:'
          - name: ':memo:'
            description: '(docs) ğŸ“ Add or modify documents'
            value: ':memo: docs:'
          - name: ':bulb'
            description: '(docs) ğŸ’¡ Adding or modifying comments to the source code'
            value: ':bulb: docs:'
          - name: ':art:'
            description: '(style) ğŸ¨ Layout related fixes'
            value: ':art: style:'
          - name: ':lipstick:'
            description: '(style) ğŸ’„ Lint: Fix errors and code style'
            value: ':lipstick: style:'
          - name: ':recycle:'
            description: '(refactor) â™»ï¸  Refactor'
            value: ':recycle: refactor:'
          - name: ':fire:'
            description: '(refactor) ğŸ”¥ Delete code or files'
            value: ':fire: refactor:'
          - name: ':green_heart:'
            description: '(test) ğŸ’š Testing and CI fixes'
            value: ':green_heart: test:'
          - name: ':rocket:'
            description: '(perf) ğŸš€ Performance improvement'
            value: ':rocket: perf:'
          - name: ':wrench:'
            description: '(chore) ğŸ”§ Modifying the configuration file'
            value: ':wrench: chore:'
          - name: ':building_construction:'
            description: '(chore) ğŸ—ï¸ Architecture fixes'
            value: ':building_construction: chore:'
          - name: ':construction:'
            description: '(wip) ğŸš§ Working on'
            value: ':construction: wip:'
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Type}}: {{.Form.Message}}'. Is this okay?"
    command: "bash -c 'type=\"{{.Form.Type}}\"; message=\"{{.Form.Message}}\"; commit_message=\"$type: $message\"; git commit -m \"$commit_message\"'"
    loadingText: "Commiting..."
